apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: shop-data
  namespace: dev-live
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: shop-data
spec:
  env:
  # TODO: DB secrets to be removed once Service Binding is enabled
  # In the meantime - perform the following:
  # kubectl patch secret ${CROSSPLANE_SECRET_NAME} \
  #   --type=json \
  #   --patch="[{ 'op': 'replace', 'path': '/metadata/name', 'value': 'shop-data-secrets' }, {'op': 'remove', 'path': '/metadata/resourceVersion'}, {'op': 'remove', 'path': '/metadata/uid'}]" \
  #   --dry-run=client \
  #   --namespace dev-live \
  #   -o yaml | kubectl apply -f -  
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: shop-data-secrets
        key: host
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: shop-data-secrets
        key: port
  - name: POSTGRES_DATABASE
    valueFrom:
      secretKeyRef:
        name: shop-data-secrets
        key: database   
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: shop-data-secrets
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: shop-data-secrets
        key: password
  - name: APP_NAME
    valueFrom:
      configMapKeyRef:
        name: shop-data-config
        key: app.name
  - name: APP_SERVICE_NAME
    valueFrom:
      configMapKeyRef:
        name: shop-data-config
        key: app.service.name
  - name: OTEL_COLLECTOR_URL
    valueFrom:
      configMapKeyRef:
        name: shop-data-config
        key: otel.collector.url
  - name: OTEL_ENABLE
    valueFrom:
      configMapKeyRef:
        name: shop-data-config
        key: otel.enable
  - name: MODE
    value: DEV
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1" 
    - name: clusterBuilder
      value: full-jammy        
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: nodejs
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build" 
  source:
    git:
      url: https://github.com/pkhamdee/shop-data.git
      ref:
        branch: main
