apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: shop-data
  namespace: sg-vbc
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: shop-data
    # TODO: to be commented out once tests are available
    # apps.tanzu.vmware.com/has-tests: "true"     
spec:
  env:
  # TODO: DB secrets to be removed once Service Binding is enabled
  # The referenced secret is based on the Classclaim-created secret
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: 0d59357c-1330-43f0-9fc1-e02caf3175e8
        key: host
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: 0d59357c-1330-43f0-9fc1-e02caf3175e8
        key: port
  - name: POSTGRES_DATABASE
    valueFrom:
      secretKeyRef:
        name: 0d59357c-1330-43f0-9fc1-e02caf3175e8
        key: database   
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: 0d59357c-1330-43f0-9fc1-e02caf3175e8
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: 0d59357c-1330-43f0-9fc1-e02caf3175e8
        key: password
  - name: MODE
    value: DEV
  - name: APP_NAME
    value: shop-data
  - name: APP_SERVICE_NAME
    value: backend
  - name: OTEL_COLLECTOR_URL
    value: http://localhost:4318/v1/traces    
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: clusterBuilder
        value: full            
  source:
    git:
      url: https://github.com/pkhamdee/shop-data.git
      ref:
        branch: main
